name = "voxelbim"
main = "aps-worker/index.js"
compatibility_date = "2024-01-01"

# Configuración para Cloudflare Pages
[site]
bucket = "./visor/dist"

[env.pages]
vars = { ENVIRONMENT = "production" }
